=== Pernod70/SwissCenter/trunk/swisscenter/xml/movies.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.swisscenter.co.uk" elementFormDefault="qualified" xmlns="http://tempuri.org/XMLSchema.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sc="http://www.swisscenter.co.uk">
  <!-- Type definitions -->
  <!-- Actor information -->
  <xs:complexType name="actors">
    <xs:sequence>
      <xs:element name="actor" type="sc:actor" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:group name="characterGroup">
    <xs:choice>
      <xs:element name="characters" type="sc:characters"/>
      <xs:element name="character" type="xs:token"/>
    </xs:choice>
  </xs:group>
  <xs:complexType name="actor">
    <xs:sequence>
      <!--<xs:element name="characters" type="sc:characters" minOccurs="0" maxOccurs="1" />-->
      <xs:element name="name" type="xs:token" minOccurs="1" maxOccurs="1" />
      <xs:group ref="sc:characterGroup" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="characters">
    <xs:sequence>
      <xs:element name="character" type="xs:token" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- Certificate information -->
  <xs:complexType name="certificates">
    <xs:sequence>
      <xs:element name="certificate" type="sc:certificate" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="certificate">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute name="scheme" type="sc:certificateScheme" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="certificateScheme">
    <xs:restriction base="xs:token">
      <xs:enumeration value="BBFC" />
      <xs:enumeration value="MPAA" />
    </xs:restriction>
  </xs:simpleType>
  <!-- Director information -->
  <xs:complexType name="directors">
    <xs:sequence>
      <xs:element name="director" type="xs:token" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- Genre information -->
  <xs:complexType name="genres">
    <xs:sequence>
      <xs:element name="genre" type="xs:token" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- The main movie schema -->
  <xs:element name="movie">
    <xs:complexType>
      <xs:all>
        <xs:element name="title" type="xs:token" minOccurs="1" maxOccurs="1" />
        <xs:element name="synopsis" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="actors" type="sc:actors" minOccurs="0" maxOccurs="1" />
        <xs:element name="certificates" type="sc:certificates" minOccurs="0" maxOccurs="1" />
        <xs:element name="language" type="xs:token" minOccurs="0" maxOccurs="1" />
        <xs:element name="runtime" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
        <xs:element name="tagline" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="directors" type="sc:directors" minOccurs="0" maxOccurs="1" />
        <xs:element name="genres" type="sc:genres" minOccurs="0" maxOccurs="1" />
        <xs:element name="year" type="xs:integer" minOccurs="0" maxOccurs="1" />
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pernod70/SwissCenter/tags/beta/1.15.rc1/swisscenter/xml/sample_movie.xml
<?xml version="1.0" encoding="utf-8"?>

<movie xmlns="http://www.swisscenter.co.uk"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.swisscenter.co.uk movies.xsd">
  <title>Austin Powers in Goldmember</title>
  <synopsis>The 3rd installment of Austin Powers</synopsis>
  <description>
    He's found his mojo, baby, and now Austin Powers (Mike Myers) is back again in this shagadelic
    comedy-adventure! The "sshhh!" hits the fan when Dr. Evil and Mini-Me escape from prison.
    Joining forces with the superfreaky Goldmember, they kidnap Austin's father, master spy Nigel
    Powers (Michael Caine), in a dastardly time-travel scheme to take over the world. Before you
    can say "Shake Your Booty," Austin cruises to 1975 and teams up with sexy Foxxy Cleopatra
    (Beyonce Knowles) to stop Dr. Evil and Goldmember from their mischievous mayhem. With Michael
    York, Robert Wagner, Seth Green, Mindy Sterling and Verne J. Troyer.
  </description>
  <actors>
    <actor>
      <name>Mike Myers</name>
      <characters>
        <character>Austin Powers</character>
        <character>Dr. Evil</character>
        <character>Fat Bastard</character>
        <character>Goldmember</character>
      </characters>
    </actor>
    <actor>
      <name>Beyonce Knowles</name>
      <character>Foxxy Cleopatra</character>
    </actor>
    <actor>
      <name>Seth Green</name>
      <character>Scott Evil</character>
    </actor>
    <actor>
      <name>Michael York</name>
      <character>Basil Exposition</character>
    </actor>
    <actor>
      <name>Robert Wagner</name>
      <character>Number Two</character>
    </actor>
    <actor>
      <name>Fred Savage</name>
    </actor>
    <actor>
      <name>Nobu Matsuhisa</name>
    </actor>
  </actors>
  <certificates>
    <certificate region="UK">12</certificate>
    <certificate region="US">PG-13</certificate>
  </certificates>
  <genres>
    <genre>Comedy</genre>
    <genre>Action</genre>
    <genre>Adventure</genre>
  </genres>
  <directors>
    <director>Fred Flintstone</director>
  </directors>
  <language>English</language>
  <runtime>94</runtime>
  <tagline>On July 26th the Secret Will Be Exposed</tagline>
  <year>2002</year>
  <filmsites>
    <filmsite parser="lovefilm">http://www.lovefilm.com/view_dvd.php?dt_id=3043&amp;se_id=15470823&amp;se_off=1&amp;se_type=title</filmsite>
    <filmsite parser="dvdplanet">http://www.dvdplanet.com/product_listing.asp?productid=27691&amp;format=DVD</filmsite>
  </filmsites>
</movie>
